env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:prettier/recommended
plugins:
  - prettier
  - file-extension-in-import-ts
ignorePatterns:
  - "**/types/sunrise_stake.ts"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: [./tsconfig.json]
rules:
  "@typescript-eslint/strict-boolean-expressions":
    - error
    - allowNullableObject: true
  "@typescript-eslint/return-await":
    - error
    - in-try-catch
#  "import/extensions":
#    - error
#    - ignorePackages
#  "n/file-extension-in-import":
#    - error
#    - tryExtensions:
#      - ".js"
#      - ".json"
  "file-extension-in-import-ts/file-extension-in-import-ts":
    - error
