env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - ../../.eslintrc.yml
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
settings:
  react:
    version: detect
plugins:
  - react
rules:
  react/react-in-jsx-scope: "off"
  file-extension-in-import-ts/file-extension-in-import-ts: "off"
