[workspace]
types = "../client/src/types"

[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.31.1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "../tests/fixtures/id.json"

[test]
startup_wait = 20000

[scripts]
test = "yarn test:anchor"

# Programs needed for the scenario tests
[[test.genesis]]
address = "sunzv8N3A8dRHwUBvxgRDEbWKk8t7yiHR4FLRgFsTX6"
program = "../../target/deploy/sunrise_stake.so"

[[test.genesis]]
address = "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD"
program = "../tests/fixtures/marinade_finance.so"

[[test.genesis]]
address = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
program = "../tests/fixtures/blaze/spl_stake_pool.so"

[[test.genesis]]
address = "SUNFT6ErsQvMcDzMcGyndq2P31wYCFs6G6WEcoyGkGc"
program = "../tests/fixtures/impact_nft.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "../tests/fixtures/mpl_token_metadata.so"

[test.validator]
slots_per_epoch = "32"
gossip_port = 8892

# Scenario1 fixtures - mainnet accounts
[[test.validator.account]]
address = "gso1xA56hacfgTHTF4F7wN5r4jbnJsKh99vR595uybA"
filename = "../tests/fixtures/scenario1/gsol_mint.json"

[[test.validator.account]]
address = "43m66crxGfXSJpmx5wXRoFuHubhHA1GCvtHgmHW6cM1P"
filename = "../tests/fixtures/scenario1/sunrise_state.json"

[[test.validator.account]]
address = "6HQrvpMJFqMj35JqMReyhnUrRXNucAAB6FywdDu7xPKA"
filename = "../tests/fixtures/scenario1/treasury.json"

[[test.validator.account]]
address = "sunzv8N3A8dRHwUBvxgRDEbWKk8t7yiHR4FLRgFsTX6"
filename = "../tests/fixtures/scenario1/sunrise_program.json"

[[test.validator.account]]
address = "6vRu2voMXGeMzAL12epHKKQrAv3v6EVoipNdh9u9s5L3"
filename = "../tests/fixtures/scenario1/msol_token_account.json"

[[test.validator.account]]
address = "HoaRQ3dcYmK2oqXT7JzzecJjJd5NXhiiqC2J4r4NjxUu"
filename = "../tests/fixtures/scenario1/msol_token_account_authority.json"

[[test.validator.account]]
address = "98Xjwb82p87eLrrQb9u74YZmLMcT81ecpUhAeM8KyNDw"
filename = "../tests/fixtures/scenario1/staker_gsol_token_account.json"

[[test.validator.account]]
address = "48V9nmW9awiR9BmihdGhUL3ZpYJ8MCgGeUoSWbtqjicv"
filename = "../tests/fixtures/scenario1/staker_account.json"

[[test.validator.account]]
address = "stk9ApL5HeVAwPLr3TLhDXdZS8ptVu7zp6ov8HFDuMi"
filename = "../tests/fixtures/scenario1/blaze_stake_pool.json"

[[test.validator.account]]
address = "bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1"
filename = "../tests/fixtures/scenario1/bsol_mint.json"

[[test.validator.account]]
address = "LPmSozJJ8Jh69ut2WP3XmVohTjL4ipR18yiCzxrUmVj"
filename = "../tests/fixtures/scenario1/lp_mint.json"

[[test.validator.account]]
address = "6RzCneyeEqnjiWxrzqfBwHDEpTrbcSkBFFUrtMZnNjpc"
filename = "../tests/fixtures/scenario1/impact_nft_state.json"

[[test.validator.account]]
address = "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD"
filename = "../tests/fixtures/scenario1/marinade_program.json"

[[test.validator.account]]
address = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"
filename = "../tests/fixtures/scenario1/msol_mint.json"

[[test.validator.account]]
address = "8szGkuLTAux9XMgZ2vtY39jVSowEcpBfFfD8hXSEqdGC"
filename = "../tests/fixtures/scenario1/marinade_state.json"

[[test.validator.account]]
address = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
filename = "../tests/fixtures/scenario1/spl_stake_pool_program.json"

[[test.validator.account]]
address = "Aj8WR7ZGEpa8pFhRWAmcBtDxMxGnoUkQDe3Z9KncNFHL"
filename = "../tests/fixtures/scenario1/offset_tiers.json"

# User accounts from unlock transaction
[[test.validator.account]]
address = "2cf1JBUkBKsWgV9UyzUizZ6XUC3ksFinmKfzepz8Zt8F"  # User wallet
filename = "../tests/fixtures/scenario1/2cf1JBUkBKsWgV9UyzUizZ6XUC3ksFinmKfzepz8Zt8F.json"

[[test.validator.account]]
address = "9xhVTV98UUcLX9kLTMuoohM8bqNCsZANrMWQmkD9ENNu"  # User's gSOL token account
filename = "../tests/fixtures/scenario1/9xhVTV98UUcLX9kLTMuoohM8bqNCsZANrMWQmkD9ENNu.json"

[[test.validator.account]]
address = "9vTh47b4EERksHqALDtr2Psd6GfXk8LtEXXyDaat5iR"  # User's lock token account (locked gSOL)
filename = "../tests/fixtures/scenario1/9vTh47b4EERksHqALDtr2Psd6GfXk8LtEXXyDaat5iR.json"

[[test.validator.account]]
address = "6A6kNxRdN7xj1YYECPQmmJ5iHjWtdiK21LCpvUd3HVyc"  # User's lock account PDA (MODIFIED: start_epoch=0, updated_to_epoch=1 for test compatibility)
filename = "../tests/fixtures/scenario1/6A6kNxRdN7xj1YYECPQmmJ5iHjWtdiK21LCpvUd3HVyc.json"

# Impact NFT accounts
[[test.validator.account]]
address = "27CTW8NkU2YHAavDRuF43iBKUhXLGv1XMhDyhZrxw3jX"  # NFT mint account
filename = "../tests/fixtures/scenario1/27CTW8NkU2YHAavDRuF43iBKUhXLGv1XMhDyhZrxw3jX.json"

[[test.validator.account]]
address = "FxLQos1kyk4JW6rAGs8CPoP9eWXUuZTnHspQSfTFBELs"  # NFT holder token account
filename = "../tests/fixtures/scenario1/FxLQos1kyk4JW6rAGs8CPoP9eWXUuZTnHspQSfTFBELs.json"

[[test.validator.account]]
address = "9QXDinR3EaKJnoqEBvnYVdTen2GVcaxmX3AR2PUbH5qJ"  # NFT metadata account
filename = "../tests/fixtures/scenario1/9QXDinR3EaKJnoqEBvnYVdTen2GVcaxmX3AR2PUbH5qJ.json"

[[test.validator.account]]
address = "AU8mPNxSx85XRikG1ehrfpY5bHF7BHFHCEgx5Bgxx6CR"  # NFT master edition
filename = "../tests/fixtures/scenario1/AU8mPNxSx85XRikG1ehrfpY5bHF7BHFHCEgx5Bgxx6CR.json"

[[test.validator.account]]
address = "GGQGfW9zJbCiXkA65fYeocV4VckP2ngrC1ViwhNLutkS"  # NFT collection metadata
filename = "../tests/fixtures/scenario1/GGQGfW9zJbCiXkA65fYeocV4VckP2ngrC1ViwhNLutkS.json"

[[test.validator.account]]
address = "5QWkXn9fqJCeUVgLRVEc8CvN81mZDXWMa2prqmJthKk6"  # NFT collection master edition
filename = "../tests/fixtures/scenario1/5QWkXn9fqJCeUVgLRVEc8CvN81mZDXWMa2prqmJthKk6.json"

[[test.validator.account]]
address = "Bz3aDGXTumhYWhHJFJQmKzqrYZwxc6vBMBwMa1xq6d8k"  # NFT collection mint
filename = "../tests/fixtures/scenario1/Bz3aDGXTumhYWhHJFJQmKzqrYZwxc6vBMBwMa1xq6d8k.json"

[[test.validator.account]]
address = "66dcpKcdX8cBeLXTqQiomjS9xsrTkKyTUzX7ADro6rvn"  # NFT new collection mint
filename = "../tests/fixtures/scenario1/66dcpKcdX8cBeLXTqQiomjS9xsrTkKyTUzX7ADro6rvn.json"

# Additional sunrise accounts
[[test.validator.account]]
address = "A9bNHVY3XReubhkuo2dkJnb9QS8qJJB72EafHAFDHE1A"  # Epoch report account
filename = "../tests/fixtures/scenario1/A9bNHVY3XReubhkuo2dkJnb9QS8qJJB72EafHAFDHE1A.json"

[[test.validator.account]]
address = "SUNFT6ErsQvMcDzMcGyndq2P31wYCFs6G6WEcoyGkGc"  # Impact NFT program
filename = "../tests/fixtures/scenario1/SUNFT6ErsQvMcDzMcGyndq2P31wYCFs6G6WEcoyGkGc.json"

# Marinade liquidity pool accounts needed for recoverTickets
[[test.validator.account]]
address = "7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE"  # liq_pool_msol_leg
filename = "../tests/fixtures/scenario1/7GgPYjS5Dza89wV6FpZ23kUJRG5vbQ1GM25ezspYFSoE.json"

[[test.validator.account]]
address = "B1aLzaNMeFVAyQ6f3XbbUyKcH2YPHu2fqiEagmiF23VR"  # treasury_msol_account
filename = "../tests/fixtures/scenario1/B1aLzaNMeFVAyQ6f3XbbUyKcH2YPHu2fqiEagmiF23VR.json"

[[test.validator.account]]
address = "UefNb6z6yvArqe4cJHTXCqStRsKmWhGxnZzuHbikP5Q"  # liq_pool_sol_leg_pda
filename = "../tests/fixtures/scenario1/UefNb6z6yvArqe4cJHTXCqStRsKmWhGxnZzuHbikP5Q.json"

[[test.validator.account]]
address = "EyaSjUtSgo9aRD1f8LWXwdvkpDTmXAW54yoSHZRF14WL"  # liq_pool_mint_authority
filename = "../tests/fixtures/scenario1/EyaSjUtSgo9aRD1f8LWXwdvkpDTmXAW54yoSHZRF14WL.json"

[[test.validator.account]]
address = "Du3Ysj1wKbxPKkuPPnvzQLQh8oMSVifs3jGZjJWXFmHN"  # reserve_pda
filename = "../tests/fixtures/scenario1/Du3Ysj1wKbxPKkuPPnvzQLQh8oMSVifs3jGZjJWXFmHN.json"

[[test.validator.account]]
address = "HoaRQ3dcYmK2oqXT7JzzecJjJd5NXhiiqC2J4r4NjxUu"  # liq_pool_msol_leg_authority
filename = "../tests/fixtures/scenario1/HoaRQ3dcYmK2oqXT7JzzecJjJd5NXhiiqC2J4r4NjxUu.json"

[[test.validator.account]]
address = "6vRu2voMXGeMzAL12epHKKQrAv3v6EVoipNdh9u9s5L3"  # get_msol_from (sunrise msol token account)
filename = "../tests/fixtures/scenario1/6vRu2voMXGeMzAL12epHKKQrAv3v6EVoipNdh9u9s5L3.json"

[[test.validator.account]]
address = "Aw7GthzX8W15yCnMUvhBG1G1mArSu3QqXmXcmcx4ZHn8"  # liq_pool_token_account
filename = "../tests/fixtures/scenario1/Aw7GthzX8W15yCnMUvhBG1G1mArSu3QqXmXcmcx4ZHn8.json"

# bSOL accounts needed for recoverTickets
[[test.validator.account]]
address = "5zCT6KjKh62XiA8KFxW9vitrZPUFJLrunQCdnm9nFAvB"  # get_bsol_from (sunrise bSOL token account)
filename = "../tests/fixtures/scenario1/5zCT6KjKh62XiA8KFxW9vitrZPUFJLrunQCdnm9nFAvB.json"

[[test.validator.account]]
address = "Fk6knLZZoSjHg2viJLReTCPhuFgKFzcnXunuGa8QaRuP"  # get_bsol_from_authority
filename = "../tests/fixtures/scenario1/Fk6knLZZoSjHg2viJLReTCPhuFgKFzcnXunuGa8QaRuP.json"